server:
  port: 8080

spring:
  application:
    name: blog-gateway
  cloud:
    gateway:
      routes:
        - id: blog-auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: blog-user
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: blog-article
          uri: http://localhost:8083
          predicates:
            - Path=/api/article/**
          filters:
            - StripPrefix=2
        - id: blog-category
          uri: http://localhost:8084
          predicates:
            - Path=/api/category/**
          filters:
            - StripPrefix=2
        - id: blog-comment
          uri: http://localhost:8085
          predicates:
            - Path=/api/comment/**
          filters:
            - StripPrefix=2

logging:
  level:
    com.demetrius.blog.gateway: debug
